import { StyleSheet } from 'react-native';

export const getSplitStyles = (COLORS, isMobile) =>
  StyleSheet.create({
    container: {
      flex: 1,
      flexDirection: 'row',
      backgroundColor: COLORS.background,
    },
    themeToggle: {
      position: 'absolute',
      top: 50,
      right: 20,
      zIndex: 50,
      padding: 10,
      borderRadius: 50,
      elevation: 5,
      shadowColor: '#000',
      shadowOffset: { width: 0, height: 2 },
      shadowOpacity: 0.2,
      shadowRadius: 4,
      backgroundColor: COLORS.surface,
    },
    brandSide: {
      flex: 1,
      backgroundColor: '#0F0F0F',
      justifyContent: 'center',
      alignItems: 'center',
      position: 'relative',
      overflow: 'hidden',
    },
    brandOverlay: {
      ...StyleSheet.absoluteFillObject,
      backgroundColor: 'rgba(0,0,0,0.4)',
    },
    decoCircle: {
      position: 'absolute',
      width: 600,
      height: 600,
      borderRadius: 300,
      borderWidth: 2,
      top: -100,
      left: -100,
    },
    decoCircleSmall: {
      position: 'absolute',
      width: 300,
      height: 300,
      borderRadius: 150,
      bottom: -50,
      right: -50,
    },
    brandContent: {
      zIndex: 10,
      alignItems: 'center',
      padding: 40,
    },
    brandTitle: {
      color: COLORS.primary,
      fontSize: 48,
      fontWeight: 'bold',
      letterSpacing: 4,
      marginBottom: 8,
    },
    brandSubtitle: {
      color: '#FFFFFF',
      fontSize: 18,
      textTransform: 'uppercase',
      letterSpacing: 2,
    },
    divider: {
      width: 80,
      height: 4,
      backgroundColor: COLORS.primary,
      marginVertical: 24,
    },
    quote: {
      color: 'rgba(255,255,255,0.7)',
      fontStyle: 'italic',
      textAlign: 'center',
      fontSize: 16,
      maxWidth: 300,
    },
    formSide: {
      flex: isMobile ? 1 : 1,
      maxWidth: isMobile ? '100%' : 600,
      backgroundColor: COLORS.background,
      justifyContent: 'center',
    },
    scrollContent: {
      flexGrow: 1,
      justifyContent: 'center',
      alignItems: 'center',
      padding: 24,
    },
    mobileHeader: {
      alignItems: 'center',
      marginBottom: 40,
      marginTop: 40,
    },
    mobileTitle: {
      color: COLORS.primary,
      fontSize: 24,
      fontWeight: 'bold',
      letterSpacing: 2,
      marginTop: 10,
    },
    formCard: {
      width: '100%',
      backgroundColor: COLORS.surface,
      padding: 32,
      borderRadius: 24,
      shadowColor: COLORS.mode === 'dark' ? '#000' : '#888',
      shadowOffset: { width: 0, height: 10 },
      shadowOpacity: 0.1,
      shadowRadius: 20,
      elevation: 10,
      borderWidth: 1,
      borderColor: COLORS.border,
    },
    formTitle: {
      fontSize: 32,
      fontWeight: 'bold',
      color: COLORS.text,
      marginBottom: 8,
    },
    formSubtitle: {
      fontSize: 16,
      color: COLORS.textSecondary,
      marginBottom: 32,
    },
    inputGroup: {
      marginBottom: 20,
    },
    label: {
      color: COLORS.textSecondary,
      fontSize: 14,
      fontWeight: '600',
      marginBottom: 8,
      marginLeft: 4,
    },
    inputWrapper: {
      flexDirection: 'row',
      alignItems: 'center',
      backgroundColor: COLORS.inputBg,
      borderRadius: 12,
      borderWidth: 1,
      borderColor: COLORS.border,
      paddingHorizontal: 16,
      height: 56,
    },
    input: {
      flex: 1,
      marginLeft: 12,
      color: COLORS.text,
      fontSize: 16,
      height: '100%',
      backgroundColor: 'transparent',
    },
    errorText: {
      color: COLORS.error,
      fontSize: 12,
      marginTop: 4,
      marginLeft: 4,
    },
    linkText: {
      color: COLORS.primary,
      fontSize: 14,
      fontWeight: '500',
    },
    primaryBtn: {
      backgroundColor: COLORS.primary,
      borderRadius: 12,
      height: 56,
      justifyContent: 'center',
      alignItems: 'center',
      marginTop: 10,
      marginBottom: 24,
      shadowColor: COLORS.primary,
      shadowOffset: { width: 0, height: 4 },
      shadowOpacity: 0.3,
      shadowRadius: 8,
      elevation: 5,
    },
    primaryBtnText: {
      color: COLORS.white,
      fontSize: 16,
      fontWeight: 'bold',
      letterSpacing: 1,
    },
    footerRow: {
      flexDirection: 'row',
      justifyContent: 'center',
      alignItems: 'center',
    },
  });

